### ISSUE TITLE
Different Output of SV12_Core from Zenmonitor

### ISSUE THREAD

**Issue by budimanjojo** [ocerman/zenpower#16]
Hello, I'm using Ryzen 5 3600 with Gigabyte B450 AORUS PRO motherboard. I have a conky script displaying the output on my desktop and my SV12_Core stays at 1.4 V constantly (not going down even on 2.5GHz idle). And I installed zenmonitor and I've got different result. In zenmonitor, the CPU Core Voltage (SV12) goes up and down depending on the CPU frequency (1.1 V on idle and 1.4 V on boost). So why is the core voltage displaying differently? Here's a screenshot showing it.
![screenshot-2020-01-19_13-46-12](https://user-images.githubusercontent.com/13085918/72676351-f5cada80-3ac2-11ea-8379-9caab19bbac1.png)
![screenshot-2020-01-19_13-53-39](https://user-images.githubusercontent.com/13085918/72676374-29a60000-3ac3-11ea-833f-80c390b78c98.png)

Here's a screencast showing it with `watch 0.5 sensors` command compared to zenmonitor:

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/13085918/72676770-9b804880-3ac7-11ea-9392-cb734dd0bdf8.gif)

**Comment by ocerman** [comment]
Hello,

What kind of cpu governor are you using? It is possible that your CPU governor is too aggressive and the conky/sensors update function is causing enough load for CPU to rise voltage and clocks. 

I had similar problem with hardinfo (issue https://github.com/lpereira/hardinfo/issues/312), but managed to change the code to be more effective and do not cause this issue anymore (https://github.com/lpereira/hardinfo/pull/327)

Anyway - the zenmonitor's update function is as lightweight as possible, that's why this is not an issue there.

Can you tell me how are you reading sensor values for conky?
I think that best way would be to read raw values from `/sys/class/hwmon/hwmon[num]/`

If you are parsing sensors output, you can try watch only zenpower: `watch -n 0.5 sensors zenpower-*`

Let me know if it helps.

**Comment by budimanjojo** [comment]
I was using ondemand cpu governor. And this is what I have for the conky:
```
${color2}CPU Core Voltage ${alignr}${color0}${hwmon 0 vol 1} V
```
And actually if I changed the governor to `conservative` then it's showing right. What's weird is zenmonitor always showing the right value but the conky doesn't show the right value with ondemand. Maybe you are right about conky hwmon command being not effective or there's something wrong with ondemand governor.

**Comment by ocerman** [comment]
Try this:
```
${color2}CPU Core Voltage ${alignr}${color0}${exec awk '{printf "%3.2fV", $1/1000}' /sys/class/hwmon/hwmon0/in1_input }
```

**Comment by budimanjojo** [comment]
It actually works great now, thanks!

**Comment by ocerman** [comment]
np
